### model
model_name_or_path: Qwen/Qwen3-VL-2B-Thinking
image_max_pixels: 8000000            
video_max_pixels: 65536      
trust_remote_code: true
video_maxlen: 64
#video_fps: 1.0


### method
stage: sft
do_train: true
finetuning_type: full            
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: /home/seohyun/vid_understanding/video_retrieval/script/sft/train/config/deepspeed/ds_z3_config.json

# Thinking 모델 옵션
enable_thinking: true        
        

### dataset
dataset: test_mllm_video_demo_hf
template: qwen3_vl              
cutoff_len: 2048000000
max_samples: 40
overwrite_cache: true
preprocessing_num_workers: 32
dataloader_num_workers: 16
dataset_dir: /home/seohyun/vid_understanding/video_retrieval/script/sft/train/data_config
media_dir: /home/seohyun/vid_understanding/video_retrieval/SFT/sft_trainer/LLaMA-Factory/data

### output
output_dir: /hub_data2/seohyun/saves/qwen3vl-2b-thinking/full/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500